Store mvim path on install
This allows the Homebrew depedency to be removed. As long as mvim is in the
users path, we don't care how it got there.

This also adds some checks to make vim-anywhere resilient if mvim moves or is
uninstalled.

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -8,6 +8,19 @@
 # file to the system clipboard.
 
 ###
+# defs
+###
+
+err() { echo -e "$@" 1>&2; }
+
+require_file_exists() {
+  if [ ! -e $1 ]; then
+    err "$1 does not exist. $2"
+    exit 1
+  fi
+}
+
+###
 # opts
 ###
 
@@ -22,6 +35,7 @@ done
 # run
 ###
 
+aw_path=$HOME/.vim-anywhere
 dir=/tmp/vim-anywhere
 file=$dir/doc-$(date +"%y%m%d%H%M%S")
 mkdir -p $dir
@@ -35,8 +49,18 @@ if [[ "$OSTYPE" == "linux-gnu" ]]; then
 
 # OSX
 elif [[ "$OSTYPE" == "darwin"* ]]; then
-  app=$(osascript $HOME/.vim-anywhere/script/current_app.scpt)
-  /usr/local/bin/mvim --nofork $file # absolute path is required here
+  # if there is no path file, it must have been deleted or the installer failed
+  require_file_exists $aw_path/.path \
+    "Please reinstall vim-anywhere."
+
+  app=$(osascript $aw_path/script/current_app.scpt)
+  mvim_path=$(cat $aw_path/.path)
+
+  require_file_exists $mvim_path/s \
+    "mvim must have been move or uninstalled.\nPlease make sure it is available in your path and then reinstall vim-anywhere."
+
+  $mvim_path --nofork $file
+  # todo, fix invalid file
   pbcopy < $file
   osascript -e "activate application \"$app\""
 fi
